name: Snyk Security Scan
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Show java
        run: |
          echo $JAVA_HOME
          echo $PATH
          java -version
  
      - name: Build with Maven
        run: mvn package -DskipTests

      - name: Run Snyk to check Maven dependencies for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --json-file-output=maven-results.json
